CREATE TABLE budget_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  entry_type VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);